# Generated by Django 4.0.4 on 2022-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_name_alter_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='done',
            field=models.BooleanField(blank=True, default=False, verbose_name='feito'),
        ),
    ]
