# Generated by Django 4.0.4 on 2022-06-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_list_created_at_list_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='list',
            name='updated_at',
        ),
    ]
